version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hublocal
      - DB_SYNCHRONIZE=false
      - DB_LOGGING=true
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=1d
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hublocal
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 