[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://hublocal-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 