services:
  - type: web
    name: hublocal-backend
    runtime: docker
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: hublocal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hublocal-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: hublocal-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: hublocal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hublocal-db
          property: password
      - key: DB_SYNCHRONIZE
        value: "false"
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        value: "8f7fc1d56cb96bfe2dc217142cbc8192d42da63adf3415bcc582184956b25ce8"
      - key: JWT_EXPIRATION
        value: "3600s"
      - key: THROTTLE_TTL
        value: "60"
      - key: THROTTLE_LIMIT
        value: "10"

databases:
  - name: hublocal-db
    databaseName: hublocal
    user: postgres
    plan: free